"""
pip install kokoro-onnx soundfile

wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.onnx
wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin
python examples/save.py
"""

import soundfile as sf
import sys
from kokoro_onnx import Kokoro

if(len(sys.argv) >= 2):
    print(sys.argv[1])

kokoro = Kokoro("kokoro-v1.0.onnx", "voices-v1.0.bin")
text = f'Hello. This audio generated by kokoro! {sys.argv[1]}'
samples, sample_rate = kokoro.create(
    text, voice="af_sarah", speed=1.0, lang="en-us"
)
sf.write("audio.wav", samples, sample_rate)
print("Created audio.wav")

